version: 2.1

orbs:
  helm: circleci/helm@3.0.2

jobs:
  build:
    docker:
      - image: cimg/base:2024.09
    steps:
      - checkout
      - helm/install_helm_client
      - helm/install_helm_plugin:
          helm_plugin_url: https://github.com/helm-unittest/helm-unittest
      - run:
          name: Run unit tests
          command: helm unittest full-compliant simple-with-envs

workflows:
  helm_test:
    jobs:
      - build
